version: '3.4'

services:
  api:
    container_name: api
    build:
      context: ./notification_api/
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8000"

  db:
    image: postgres:15.0-alpine
    container_name: postgres
    volumes:
#      - postgres_volume:/var/lib/postgresql/data/
      - ./deploy/postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    ports:
      - "5672"
      - "15672"

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/configs:/etc/nginx/conf.d:ro
    ports:
      - '80:80'
    depends_on:
      - api

  sender:
    container_name: sender
    build: sender/
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
